spring.application.name=Japlearn
spring.data.mongodb.uri=mongodb+srv://bacolod2186_db_user:9vZpu0EyMOp6maW4@cluster0.qfmwks5.mongodb.net/japlearn?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=japlearn
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=ac5528001@smtp-brevo.com
spring.mail.password=EYUTIF9WkmK8pxJv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.security.user.name=bacolod2186_db_user 
spring.security.user.password=9vZpu0EyMOp6maW4
spring.servlet.multipart.enabled = true
spring.servlet.multipart.max-file-size = 200MB
spring.servlet.multipart.max-request-size = 200MB

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure.web.servlet=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=DEBUG
logging.level.org.apache.tomcat=DEBUG
server.port=8080
app.base-url=http://localhost:8080




