package japlearn.demo.Controller;

import static japlearn.demo.Service.GuidedPracticeClockService.DAILY_LIMIT_SECONDS;
import java.time.*;
import java.util.*;
import org.springframework.http.*;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import japlearn.demo.Entity.*;
import japlearn.demo.Repository.*;
import japlearn.demo.Service.*;

@RestController
@RequestMapping("/api/guidedPractice")
public class GeminiGuidedPracticeController {
 private static final ZoneId ZONE=ZoneId.of("Asia/Manila");
 private final GuidedPracticeScenarioRepository scenarios; private final GuidedPracticeUsageRepository usage; private final QuackTalkSessionRepository sessions; private final AzureSpeechService speech; private final GuidedAudioNormalizer audioNormalizer; private final GeminiLiveTokenService gemini; private final GuidedPracticeClockService clock; private final ApiAccessService access;
 public GeminiGuidedPracticeController(GuidedPracticeScenarioRepository scenarios,GuidedPracticeUsageRepository usage,QuackTalkSessionRepository sessions,AzureSpeechService speech,GuidedAudioNormalizer audioNormalizer,GeminiLiveTokenService gemini,GuidedPracticeClockService clock,ApiAccessService access){this.scenarios=scenarios;this.usage=usage;this.sessions=sessions;this.speech=speech;this.audioNormalizer=audioNormalizer;this.gemini=gemini;this.clock=clock;this.access=access;}
 @GetMapping("/scenarios") public List<GuidedPracticeScenario> published(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth){access.require(auth,null,"student","teacher","admin");return scenarios.findByPublishedTrueOrderByTitleAsc();}
 @GetMapping("/scenarios/admin") public List<GuidedPracticeScenario> all(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth){access.require(auth,null,"teacher","admin");return scenarios.findAll();}
 @PostMapping("/scenarios/admin") public GuidedPracticeScenario create(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@RequestBody GuidedPracticeScenario s){access.require(auth,null,"teacher","admin");s.setId(null);validate(s);return scenarios.save(s);}
 @PutMapping("/scenarios/admin/{id}") public GuidedPracticeScenario update(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@PathVariable String id,@RequestBody GuidedPracticeScenario s){access.require(auth,null,"teacher","admin");if(!scenarios.existsById(id))throw new NoSuchElementException();s.setId(id);validate(s);return scenarios.save(s);}
 @DeleteMapping("/scenarios/admin/{id}") public ResponseEntity<Void> delete(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@PathVariable String id){access.require(auth,null,"admin");scenarios.deleteById(id);return ResponseEntity.noContent().build();}
 @GetMapping("/allowance") public Map<String,Integer> allowance(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@RequestParam String email){access.require(auth,email,"teacher","admin");int used=today(email).getSecondsUsed();return Map.of("dailyLimitSeconds",DAILY_LIMIT_SECONDS,"usedSeconds",used,"remainingSeconds",Math.max(0,DAILY_LIMIT_SECONDS-used));}
 @PostMapping("/sessions/start") public synchronized ResponseEntity<?> start(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@RequestBody StartRequest request){User user=access.require(auth,request.email(),"teacher","admin");for(QuackTalkSession active:sessions.findByEmailIgnoreCaseAndRoomTypeAndStatus(user.getEmail(),"GUIDED_PHRASE","ACTIVE")){clock.bill(active);finish(active,false);}int remaining=DAILY_LIMIT_SECONDS-today(user.getEmail()).getSecondsUsed();if(remaining<=0)return ResponseEntity.status(429).body(Map.of("message","Your 20-minute Guided Practice allowance is complete for today.","remainingSeconds",0));GuidedPracticeScenario scenario=selectScenario(request.scenarioId());GeminiLiveTokenService.Token token=gemini.issue(scenario,remaining);QuackTalkSession s=new QuackTalkSession();s.setEmail(user.getEmail());s.setName(((user.getFname()==null?"":user.getFname())+" "+(user.getLname()==null?"":user.getLname())).trim());s.setRoomType("GUIDED_PHRASE");s.setLanguage("JAPANESE");s.setScenarioId(scenario.getId());s.setScenarioTitle(scenario.getTitle());s.setStartedAt(Instant.now());s.setUsageRecordedAt(Instant.now());s.setPracticedAt(Instant.now());s.setStatus("ACTIVE");s.setEvaluated(true);sessions.save(s);Map<String,Object> out=base(s,scenario,remaining);out.put("geminiToken",token.name());out.put("geminiModel",token.model());out.put("sumiVoice",token.voice());return ResponseEntity.ok(out);}
 @PostMapping(value="/sessions/{id}/pronunciation",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public synchronized ResponseEntity<?> pronunciation(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@PathVariable String id,@RequestPart("audio")MultipartFile audio,@RequestPart(value="hintsUsed",required=false)String hints)throws Exception{QuackTalkSession s=owned(auth,id);if(!"ACTIVE".equals(s.getStatus()))return ResponseEntity.status(409).body(Map.of("message","This Guided Practice session has ended.","completed",true));clock.bill(s);int remaining=DAILY_LIMIT_SECONDS-today(s.getEmail()).getSecondsUsed();if(remaining<=0){finish(s,false);return ResponseEntity.status(429).body(Map.of("message","Today’s 20-minute practice is complete. Sumi saved your progress.","completed",true,"remainingSeconds",0));}byte[] wav=audioNormalizer.toAzureWav(audio.getBytes(),audio.getContentType());AzureSpeechService.SpeechResult a=speech.assess(wav,"audio/wav");QuackTalkSession.Turn t=new QuackTalkSession.Turn();t.setTranscript(a.transcript());t.setPronunciation(a.pronunciation());t.setAccuracy(a.accuracy());t.setFluency(a.fluency());t.setHintsUsed(Math.max(0,Math.min(parse(hints),4)));s.getTurns().add(t);s.setConversationTurns(s.getTurns().size());s.setHintsUsed(s.getHintsUsed()+t.getHintsUsed());calculate(s);sessions.save(s);Map<String,Object> out=new LinkedHashMap<>();out.put("turnIndex",s.getTurns().size()-1);out.put("transcript",a.transcript());out.put("pronunciation",a.pronunciation());out.put("accuracy",a.accuracy());out.put("fluency",a.fluency());out.put("pcmBase64",Base64.getEncoder().encodeToString(audioNormalizer.wavToPcm(wav)));out.put("remainingSeconds",remaining);return ResponseEntity.ok(out);}
 @PostMapping("/sessions/{id}/turn-result") public synchronized QuackTalkSession turnResult(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@PathVariable String id,@RequestBody TurnResult r){QuackTalkSession s=owned(auth,id);if(r.turnIndex()>=0&&r.turnIndex()<s.getTurns().size()){QuackTalkSession.Turn t=s.getTurns().get(r.turnIndex());t.setSumiJapanese(trim(r.sumiJapanese(),1000));t.setFeedback(trim(r.feedback(),500));t.setRegister(trim(r.register(),40));t.setContextuallyAppropriate(r.contextuallyAppropriate());s.setCurrentSumiJapanese(t.getSumiJapanese());}calculate(s);sessions.save(s);return s;}
 @GetMapping("/sessions/{id}/hint") public Map<String,Object> hint(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@PathVariable String id,@RequestParam(defaultValue="1")int level){QuackTalkSession s=owned(auth,id);GuidedPracticeScenario scenario=scenarios.findById(s.getScenarioId()).orElseThrow();List<String> h=scenario.getProgressiveHints()==null?List.of():scenario.getProgressiveHints().stream().limit(4).toList();if(h.isEmpty())return Map.of("level",0,"hint","Listen for Sumi’s main question and answer the main idea naturally.");int i=Math.max(0,Math.min(level-1,h.size()-1));return Map.of("level",i+1,"hint",h.get(i));}
 @PostMapping("/sessions/{id}/end") public synchronized QuackTalkSession end(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@PathVariable String id){QuackTalkSession s=owned(auth,id);if("ACTIVE".equals(s.getStatus())){clock.bill(s);finish(s,false);}return s;}
 @GetMapping("/sessions") public List<QuackTalkSession> history(@RequestHeader(HttpHeaders.AUTHORIZATION)String auth,@RequestParam String email){access.require(auth,email,"teacher","admin");return sessions.findByEmailIgnoreCaseOrderByPracticedAtDesc(email).stream().filter(s->"GUIDED_PHRASE".equals(s.getRoomType())).toList();}
 private QuackTalkSession owned(String auth,String id){QuackTalkSession s=sessions.findById(id).orElseThrow();access.require(auth,s.getEmail(),"teacher","admin");return s;} private GuidedPracticeUsage today(String email){LocalDate d=LocalDate.now(ZONE);return usage.findByEmailIgnoreCaseAndDate(email,d).orElseGet(()->{GuidedPracticeUsage u=new GuidedPracticeUsage();u.setEmail(email.toLowerCase());u.setDate(d);return u;});}
 private Map<String,Object> base(QuackTalkSession s,GuidedPracticeScenario x,int remaining){Map<String,Object> o=new LinkedHashMap<>();o.put("sessionId",s.getId());o.put("scenarioId",x.getId());o.put("scenarioTitle",x.getTitle());o.put("roleName",x.getRoleName());o.put("introduction",x.getIntroduction());o.put("objective",x.getObjective());o.put("remainingSeconds",Math.max(0,remaining));o.put("dailyLimitSeconds",DAILY_LIMIT_SECONDS);return o;} private GuidedPracticeScenario selectScenario(String id){if(id!=null&&!id.isBlank())return scenarios.findById(id).filter(GuidedPracticeScenario::isPublished).orElseThrow();List<GuidedPracticeScenario>a=scenarios.findByPublishedTrueOrderByTitleAsc();if(a.isEmpty())throw new IllegalStateException("No published Guided Practice scenario is available.");return a.get((int)(System.currentTimeMillis()/86_400_000L%a.size()));}
 private void calculate(QuackTalkSession s){List<QuackTalkSession.Turn>t=s.getTurns();if(t.isEmpty())return;s.setAveragePronunciationScore(avg(t.stream().map(QuackTalkSession.Turn::getPronunciation).toList()));s.setAverageAccuracyScore(avg(t.stream().map(QuackTalkSession.Turn::getAccuracy).toList()));s.setAverageFluencyScore(avg(t.stream().map(QuackTalkSession.Turn::getFluency).toList()));s.setContextualAccuracy((int)Math.round(t.stream().filter(QuackTalkSession.Turn::isContextuallyAppropriate).count()*100d/t.size()));s.setScore((s.getAveragePronunciationScore()+s.getAverageAccuracyScore()+s.getAverageFluencyScore()+s.getContextualAccuracy())/4);} private void finish(QuackTalkSession s,boolean complete){calculate(s);s.setStatus("ENDED");s.setCompleted(complete);s.setEndedAt(Instant.now());s.setPracticedAt(Instant.now());if(s.getFeedbackSummary()==null)s.setFeedbackSummary("Sumi saved this live conversation. Review your pronunciation and conversation history before the next practice.");sessions.save(s);}
 private int avg(List<Integer>v){return(int)Math.round(v.stream().filter(Objects::nonNull).mapToInt(Integer::intValue).average().orElse(0));}private int parse(String v){try{return Integer.parseInt(v);}catch(Exception e){return 0;}}private String trim(String v,int n){return v==null?null:v.substring(0,Math.min(v.length(),n));}private void validate(GuidedPracticeScenario s){if(s.getTitle()==null||s.getTitle().isBlank()||s.getObjective()==null||s.getObjective().isBlank())throw new IllegalArgumentException("Scenario title and objective are required.");}
 public record StartRequest(String email,String scenarioId){} public record TurnResult(int turnIndex,String sumiJapanese,String feedback,String register,boolean contextuallyAppropriate){}
}
